services:

  postgres:
    image: postgres:17.5
    container_name: chat-postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 5s
      timeout: 5s
      retries: 10


  backend:
    build:
      context: ./chat-spring-boot
      dockerfile: Dockerfile

    container_name: chat-backend

    restart: unless-stopped

    environment:
      BACKEND_PORT: ${BACKEND_PORT}

      DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      DATASOURCE_USERNAME: ${POSTGRES_USER}
      DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      DATASOURCE_VERSION: ${DATASOURCE_VERSION}
      DATASOURCE_SCHEMA: ${DATASOURCE_SCHEMA}

      DATASOURCE_DRIVER_CLASS_NAME: ${DATASOURCE_DRIVER_CLASS_NAME}
      HIBERNATE_DDL_AUTO: ${HIBERNATE_DDL_AUTO}

    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"

    depends_on:
      postgres:
        condition: service_healthy


  frontend:
    build:
      context: ./chat-frontend
      dockerfile: Dockerfile

    container_name: chat-frontend

    restart: unless-stopped

    environment:
      SERVER_API_URL: ${SERVER_API_URL}
      VITE_API_URL: ${VITE_API_URL}
 

    ports:
      - "3000:3000"

    depends_on:
      - backend


volumes:
  postgres_data:
